import createPlotlyComponent from 'react-plotly.js/factory';
import Plotly from 'plotly.js-basic-dist-min';
import type { Layout, Data, PlotMouseEvent, PlotlyHTMLElement } from 'plotly.js';
import type { Observation, ProfileResult, Variable } from '../types';
import type { compareProfiles } from '../analysis';
const Plot=createPlotlyComponent(Plotly);
type Pair=ReturnType<typeof compareProfiles>['pairs'][number];
export default function ComparisonCharts({current,reference,variable,pairs,onCurrent,onReference}:{current:ProfileResult;reference:ProfileResult;variable:Variable;pairs:Pair[];onCurrent:(o:Observation)=>void;onReference:(o:Observation)=>void}) {
  const units=variable==='temperature'?'°C':'PSS-78';
  // Rebind after initialization/update: StrictMode's mount/purge cycle clears Plotly listeners.
  const overlayClick=(e:PlotMouseEvent)=>{const p=e.points[0];if(!p)return;const r=p.curveNumber===0?current:reference;const o=r.observations[p.pointIndex];if(o)(p.curveNumber===0?onCurrent:onReference)(o);};
  const differenceClick=(e:PlotMouseEvent)=>{const p=pairs[e.points[0]?.pointIndex];if(p)onCurrent(p.a);};
  const bind=(graph:PlotlyHTMLElement, handler:(e:PlotMouseEvent)=>void)=>{graph.removeAllListeners('plotly_click');graph.on('plotly_click',handler);};

  const layout:Partial<Layout>={autosize:true,height:310,margin:{l:58,r:18,t:38,b:50},paper_bgcolor:'transparent',plot_bgcolor:'transparent',font:{family:'Segoe UI, sans-serif',size:10,color:'#68818a'},yaxis:{title:{text:'Depth (m)'},range:[Math.max(current.plan.max_depth,reference.plan.max_depth),Math.min(current.plan.min_depth,reference.plan.min_depth)],gridcolor:'#edf1f2',zeroline:false},xaxis:{title:{text:units},gridcolor:'#edf1f2',zeroline:false},legend:{orientation:'h',x:0,y:1.12},hovermode:'closest',dragmode:false};
  const observed=[current,reference].map((r,i):Data=>({type:'scatter',mode:'markers',name:i?'Reference':'Current',x:r.observations.map(o=>o[variable]),y:r.observations.map(o=>o.depth_m),marker:{size:5,color:i?'#bc8242':'#087f79',symbol:i?'diamond-open':'circle'},hovertemplate:`${i?'Reference':'Current'}: %{x:.3f} ${units}<br>%{y:.1f} m<extra></extra>`}));
  return <div className="comparison-charts"><section aria-label="Overlaid observed profiles"><h3>Observed profiles</h3><Plot data={observed} layout={layout} config={{responsive:true,displayModeBar:false}} style={{width:'100%',height:310}} useResizeHandler onInitialized={(_,g)=>bind(g as PlotlyHTMLElement,overlayClick)} onUpdate={(_,g)=>bind(g as PlotlyHTMLElement,overlayClick)}/><p>Markers only: unsampled depths remain unconnected. Click either profile for evidence.</p></section><section aria-label="Paired difference by depth"><h3>Current − reference</h3>{pairs.length?<Plot data={[{type:'scatter',mode:'markers',x:pairs.map(p=>p.delta),y:pairs.map(p=>p.a.depth_m),text:pairs.map(p=>`Reference depth ${p.b.depth_m.toFixed(1)} m · offset ${p.depthOffset.toFixed(2)} m`),marker:{size:6,color:'#607bbb'},hovertemplate:`%{x:+.3f} ${units}<br>Current depth %{y:.1f} m<br>%{text}<extra></extra>`}]} layout={{...layout,showlegend:false,xaxis:{...layout.xaxis,title:{text:`Difference (${units})`},zeroline:true,zerolinecolor:'#aab8bd',zerolinewidth:1},shapes:[{type:'line',xref:'x',x0:0,x1:0,yref:'paper',y0:0,y1:1,line:{color:'#aab8bd',dash:'dot',width:1}}]}} config={{responsive:true,displayModeBar:false}} style={{width:'100%',height:310}} useResizeHandler onInitialized={(_,g)=>bind(g as PlotlyHTMLElement,differenceClick)} onUpdate={(_,g)=>bind(g as PlotlyHTMLElement,differenceClick)}/>:<div className="chart-empty">No matched observations at this tolerance.</div>}<p>Differences plotted at current sample depths. Use the paired table for evidence from both observations.</p></section></div>;
}
