import { useEffect, useState } from 'react';
import { getJSON } from '../api';
interface Status {active_snapshot_id?:string;state:string;message:string;checked_at?:string;latest_observation?:string;snapshot_id?:string;files_checked?:number;cycles_per_float?:number;file_limit?:number}
export default function DataFreshness({snapshotId}:{snapshotId:string}) {
  const [status,setStatus]=useState<Status|null>(null);
  const [cycles,setCycles]=useState(3);
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState('');
  useEffect(()=>{const c=new AbortController();getJSON<Status>('/api/data/status',c.signal).then(setStatus).catch(e=>{if(e.name!=='AbortError')setError('Update status unavailable. Cached data can still be explored.');});return()=>c.abort();},[]);
  useEffect(()=>{if(!busy && status?.state!=='running')return;const c=new AbortController();const timer=window.setInterval(()=>{getJSON<Status>('/api/data/status',c.signal).then(setStatus).catch(()=>{});},2000);return()=>{window.clearInterval(timer);c.abort();};},[busy,status?.state]);
  const refresh=async()=>{setBusy(true);setError('');try{const r=await fetch(`/api/data/refresh?cycles=${cycles}`,{method:'POST',headers:{'X-FloatChat-Refresh':'1'}});if(!r.ok)throw new Error('Update check unavailable. Cached data is still usable.');setStatus(await r.json());}catch(e){setError(e instanceof Error?e.message:'Update failed.');}finally{setBusy(false);}};
  return <section className="data-freshness" aria-label="Argo data updates"><div><strong>Argo data updates</strong><p>Recent ascent cycles for tracked floats: 1902674, 1902675, 1902676. On-demand GDAC checks; not a continuous live feed.</p>{status?.cycles_per_float&&<p>Last request: {status.cycles_per_float} cycles per float · {status.files_checked??0} files checked.</p>}{status?.checked_at&&<p>Last checked: {new Date(status.checked_at).toLocaleString()} {status.latest_observation&&<>· Latest observation: {status.latest_observation.slice(0,10)} UTC</>}</p>}<p role="status">{busy?`Downloading and validating up to ${cycles*3} files. ${status?.state==='running' ? status.message : 'Starting check…'}`:status?.message}</p>{error&&<p role="alert">{error}</p>}</div><div className="refresh-actions"><label>History per float<select aria-label="History cycles per float" value={cycles} disabled={busy||status?.state==='running'} onChange={e=>setCycles(Number(e.target.value))}><option value={3}>Latest 3 cycles · up to 9 files</option><option value={12}>Latest 12 cycles · up to 36 files</option><option value={24}>Latest 24 cycles · up to 72 files</option></select></label><small>Cycle counts are not calendar durations. Existing profiles are retained; older gaps can remain. Up to 10 MB per file.</small><button className="button secondary" disabled={busy||status?.state==='running'} onClick={()=>void refresh()}>{busy?'Checking GDAC…':cycles===3?'Check for new profiles':'Download recent history'}</button>{status?.snapshot_id&&status.snapshot_id!==snapshotId&&<p>Last GDAC check used {status.snapshot_id}. This workspace shows {snapshotId}.</p>}{(status?.active_snapshot_id??status?.snapshot_id)&&(status?.active_snapshot_id??status?.snapshot_id)!==snapshotId&&<button className="button primary" onClick={()=>window.location.reload()}>Reload active data</button>}</div></section>;
}
