import { lazy, Suspense, useState } from 'react';
import { ANALYSIS_METHOD, compareProfiles, comparisonContext, gradients, thermocline } from '../analysis';
import { dateLabel, type Observation, type ProfileResult, type Variable } from '../types';
import Evidence from './Evidence';
const ComparisonCharts=lazy(()=>import('./ComparisonCharts'));

export default function SciencePanel({result,onSample}:{result:ProfileResult|null;onSample:(o:Observation)=>void}) {
  const [baseline,setBaseline]=useState<ProfileResult|null>(null);
  const [lens,setLens]=useState<Variable>('temperature');
  const [gap,setGap]=useState(50);
  const [tolerance,setTolerance]=useState(5);
  const [inspect,setInspect]=useState<Observation|null>(null);
  const variables=result?.plan.variables ?? ['temperature','salinity'];
  const variable=variables.includes(lens)?lens:variables[0];
  const thermal=thermocline(result?.observations ?? [],gap);
  const salt=gradients(result?.observations ?? [],'salinity',gap).sort((a,b)=>Math.abs(b.gradient)-Math.abs(a.gradient))[0];
  const comparison=result && baseline ? compareProfiles(result,baseline,variable,tolerance):null;
  const context=result && baseline ? comparisonContext(result,baseline):null;
  const exportAnalysis=()=>{
    if(!result || !baseline || !comparison || comparison.error)return;
    const body={context,method:ANALYSIS_METHOD,variable,tolerance_m:tolerance,max_gradient_gap_m:gap,current:result,reference:baseline,thermocline:thermal,salinity_gradient:salt??null,pairs:comparison.pairs,interpretation:'Observed pairs within depth tolerance; current minus reference. No interpolation, climatology or trend inference.'};
    const url=URL.createObjectURL(new Blob([JSON.stringify(body,null,2)],{type:'application/json'}));
    const a=document.createElement('a');a.href=url;a.download=`floatchat-analysis-${result.result_id}-${baseline.result_id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
  };
  return <section className="science-panel" aria-label="Profile science lab">
    <div className="science-heading"><div><span className="eyebrow">FROM OBSERVATION TO INSIGHT</span><h2>Profile science lab</h2></div><label>Maximum gradient gap<select aria-label="Maximum gradient gap" value={gap} onChange={e=>setGap(Number(e.target.value))}><option value={25}>25 m</option><option value={50}>50 m</option><option value={100}>100 m</option></select></label></div>
    <div className="science-cards"><article><h3>Thermocline candidate</h3>{thermal.strongest ? <><strong>{thermal.strongest.a.depth_m.toFixed(1)}–{thermal.strongest.b.depth_m.toFixed(1)} m</strong><p>{thermal.strongest.gradient.toFixed(4)} °C/m · strongest observed cooling interval</p><button className="text-link" onClick={()=>onSample(thermal.strongest!.a)}>Upper sample ↗</button><button className="text-link" onClick={()=>onSample(thermal.strongest!.b)}>Lower sample ↗</button></>:<p>No eligible cooling interval in this selection.</p>}</article><article><h3>Strongest salinity gradient</h3>{salt ? <><strong>{salt.gradient>0?'+':''}{salt.gradient.toFixed(5)} PSS-78/m</strong><p>{salt.a.depth_m.toFixed(1)}–{salt.b.depth_m.toFixed(1)} m · signed change with depth</p><button className="text-link" onClick={()=>onSample(salt.a)}>Upper sample ↗</button><button className="text-link" onClick={()=>onSample(salt.b)}>Lower sample ↗</button></>:<p>No eligible salinity interval in this selection.</p>}</article></div>
    <p className="science-note">Exploratory finite differences across consecutive source levels, spaced 2–{gap} m apart. Missing values and skipped source levels break the calculation. The candidate is the strongest cooling within the selected depth band, not a validated thermocline boundary. {thermal.intervals} temperature intervals evaluated. <a href="https://oceanservice.noaa.gov/facts/thermocline.html" target="_blank" rel="noreferrer">Thermocline background ↗</a></p>
    <div className="science-heading"><div><h3>Compare with a reference</h3><p>{baseline?`Reference: ${baseline.profile.wmo} · cycle ${baseline.profile.cycle} · ${dateLabel(baseline.profile.timestamp)} · ${baseline.plan.min_depth}–${baseline.plan.max_depth} m · ${baseline.plan.qc} QC`:'Pin this selection, then choose another profile to compare.'}</p></div><button className="button secondary" disabled={!result} onClick={()=>{setBaseline(result);setInspect(null);}}>Pin current as reference</button></div>
    {baseline && <><div className="science-tools"><label>Variable<select aria-label="Comparison variable" value={variable} onChange={e=>setLens(e.target.value as Variable)}>{variables.map(v=><option key={v}>{v}</option>)}</select></label><label>Depth tolerance<select aria-label="Comparison depth tolerance" value={tolerance} onChange={e=>setTolerance(Number(e.target.value))}><option value={1}>±1 m</option><option value={5}>±5 m</option><option value={10}>±10 m</option></select></label><button className="button secondary" disabled={!comparison?.pairs.length || !!comparison.error} onClick={exportAnalysis}>Export analysis JSON</button><button className="text-link" onClick={()=>{setBaseline(null);setInspect(null);}}>Clear reference</button></div>
    {!result?<p>Select a profile to compare.</p>:baseline.profile.id===result.profile.id?<p className="science-note">This is the same profile. Select another observation to explore differences.</p>:null}
    {comparison?.error?<p role="alert" className="inline-warning">{comparison.error}</p>:comparison && <><p className="science-note">{comparison.pairs.length} one-to-one nearest-depth pairs, current minus reference. Matching proceeds shallow to deep; reference levels are never reused. Values are observed at slightly different depths; no interpolation. Float movement and differing dates prevent interpreting this as a climate trend.</p>{result && context && <><div className="comparison-context"><span><strong>{context.distance_km.toFixed(1)} km</strong> between reported locations</span><span><strong>{Math.abs(context.signed_days).toFixed(2)} days</strong> · current {context.signed_days<0?'earlier than':context.signed_days>0?'later than':'at the same time as'} reference</span></div><Suspense fallback={<p className="science-note">Preparing comparison charts…</p>}><ComparisonCharts current={result} reference={baseline} variable={variable} pairs={comparison.pairs} onCurrent={onSample} onReference={setInspect}/></Suspense></>}<div className="science-table"><table className="data-table"><caption>{variable} · {variable==='temperature'?'°C':'PSS-78'} · source links on both depths</caption><thead><tr><th>Current depth</th><th>Reference depth</th><th>Offset (m)</th><th>Current</th><th>Reference</th><th>Difference</th></tr></thead><tbody>{comparison.pairs.map(p=><tr key={p.a.source_level}><td><button className="text-link" onClick={()=>onSample(p.a)}>{p.a.depth_m.toFixed(1)} m ↗</button></td><td><button className="text-link" onClick={()=>setInspect(p.b)}>{p.b.depth_m.toFixed(1)} m ↗</button></td><td>{p.depthOffset.toFixed(2)}</td><td>{p.a[variable]?.toFixed(3)}</td><td>{p.b[variable]?.toFixed(3)}</td><td>{p.delta>0?'+':''}{p.delta.toFixed(3)}</td></tr>)}</tbody></table>{!comparison.pairs.length && <p>No eligible pairs. Adjust the tolerance or select overlapping depth bands.</p>}</div></>}
    <Evidence result={baseline} sample={inspect} open={!!inspect} onClose={()=>setInspect(null)}/></>}
  </section>;
}
