import { useEffect, useState } from 'react';
import { getJSON } from '../api';
interface Snapshot {snapshot_id:string;current:boolean;created_at:string;profile_count:number;float_count:number;first_observation:string;last_observation:string;compatible:boolean}
interface Archive {current_snapshot_id:string;snapshots:Snapshot[];unreadable_archives:number}
export default function SnapshotArchive() {
  const [archive,setArchive]=useState<Archive|null>(null);
  const [selected,setSelected]=useState('');
  const [error,setError]=useState('');
  const [busy,setBusy]=useState(false);
  const [version,setVersion]=useState(0);
  useEffect(()=>{const c=new AbortController();getJSON<Archive>('/api/data/snapshots',c.signal).then(data=>{setArchive(data);setSelected('');setError('');}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>c.abort();},[version]);
  const target=archive?.snapshots.find(s=>s.snapshot_id===selected);
  const activate=async()=>{if(!target||!archive)return;setBusy(true);setError('');try{const response=await fetch('/api/data/snapshots/activate',{method:'POST',headers:{'Content-Type':'application/json','X-FloatChat-Refresh':'1'},body:JSON.stringify({snapshot_id:target.snapshot_id,expected_current:archive.current_snapshot_id})});if(!response.ok){const data=await response.json();throw new Error(data.detail?.message??'Could not switch snapshot.');}window.location.reload();}catch(e){setError(e instanceof Error?e.message:'Snapshot switch failed.');setBusy(false);}};
  return <details className="snapshot-archive"><summary>Reopen an archived dataset</summary><p>Choose the snapshot ID from a saved investigation or evidence export. Opening it changes the active dataset for this local app and reloads the page. Unsaved filters and results reset; saved bookmarks remain.</p><button className="text-link" disabled={busy} onClick={()=>setVersion(v=>v+1)}>Refresh archive list</button>{error&&<p role="alert" className="query-error">{error}</p>}{!archive&&!error&&<p role="status">Loading local snapshot archive…</p>}{archive&&<><p>Active snapshot: <strong>{archive.current_snapshot_id}</strong></p>{archive.unreadable_archives>0&&<p>{archive.unreadable_archives} unreadable archive(s) omitted.</p>}<div className="audit-table"><table className="data-table"><thead><tr><th>Snapshot</th><th>Profiles / floats</th><th>Observation window, UTC</th><th>Action</th></tr></thead><tbody>{archive.snapshots.map(s=><tr key={s.snapshot_id}><td>{s.snapshot_id}</td><td>{s.profile_count} / {s.float_count}</td><td>{s.first_observation.slice(0,10)} → {s.last_observation.slice(0,10)}</td><td>{s.current?'Active':!s.compatible?'Incompatible method':<button className="text-link" disabled={busy} onClick={()=>setSelected(s.snapshot_id)}>Review snapshot</button>}</td></tr>)}</tbody></table></div></>}{target&&!target.current&&<div className="section-inspection"><strong>Open {target.snapshot_id}?</strong><p>{target.profile_count} profiles, {target.first_observation.slice(0,10)} through {target.last_observation.slice(0,10)}. The current snapshot will be archived so you can return to it. This does not download or update measurements.</p><button className="button primary" disabled={busy} onClick={()=>void activate()}>{busy?'Opening…':'Open snapshot and reload'}</button><button className="button secondary" disabled={busy} onClick={()=>setSelected('')}>Cancel</button></div>}<p>A snapshot switch is blocked during a data import. Other open tabs must reload after a switch; queries with the old snapshot ID are rejected.</p></details>;
}
